refactor csr manager and add test
KULeuven-MICAS/snax-streamer pull request #27
Opened 2024-03-12 14:37 UTC by jorendumoulin

2024-04-30 15:07 UTC, jorendumoulin commented
Hi @xiaoling-yi i rebased, but I had to remove some stuff related to the StreamerIdle2Busy. If we are going to reuse the csrmanager across different projects, we cannot have streamer specific stuff in this source code, right?

2024-04-30 15:13 UTC, xiaoling-yi commented
> Hi @xiaoling-yi i rebased, but I had to remove some stuff related to the StreamerIdle2Busy. If we are going to reuse the csrmanager across different projects, we cannot have streamer specific stuff in this source code, right?

Hi @jorendumoulin , this StreamerIdle2Busy signal is for the hardware performance counter. We can rename this signal as AcceIdle2Busy. Currently, GEMM, SIMD, and Streamer all have a performance counter. So I think it can be viewed as a common feature.

2024-04-30 15:58 UTC, jorendumoulin commented
Alright I looked at the code, but it really looks like a hack how it is implemented now. The code is divided between Streamer and CSR Manager, so we can not split it easily. If we want more than one performance counter/less then one performance counter, we need to add signals. Right now we are manipulating the input port to the risc-v cpu with the accelerator, which should also not happen. Can we not design the system for perfomance counters like this:

Where the number of read-only registers is a parameter, and these registers are handled by the accelerator target? Then we don't have to mess with the CSR interface to snitch.

@rgantonio 

![image](https://github.com/KULeuven-MICAS/snax-streamer/assets/47864363/322e9781-4fac-47e6-9fc1-b66676fa1820)

2024-04-30 16:24 UTC, rgantonio commented
Aha, okay I think I see what's happening now. We can generalize it to some kind of "read-only" inputs. Hmm.

2024-04-30 16:24 UTC, rgantonio commented
But wait, I thought we're ditching this snax-streamer repo and putting it on the SNAX cluster instead?

2024-04-30 18:05 UTC, jorendumoulin commented
Yes, but I want to merge the open standing PRs first

2024-05-02 07:54 UTC, jorendumoulin commented
How do you want to proceed? My suggestion is this:

1. Merge this PR
2. Put `csr_manager` in `snitch_cluster`
3. Put `streamer` in `snitch_cluster`
4. Archive this repository
5. Work on a better system for read-only status registers then to better support performance counters

Let me know what you think

2024-05-02 08:00 UTC, rgantonio commented
@jorendumoulin YES!! I prefer we fix it in the `snitch_cluster` instead so that we don't double-update things. What do you think @xiaoling-yi ?

2024-05-02 08:16 UTC, xiaoling-yi commented
> How do you want to proceed? My suggestion is this:
> 
> 1. Merge this PR
> 2. Put `csr_manager` in `snitch_cluster`
> 3. Put `streamer` in `snitch_cluster`
> 4. Archive this repository
> 5. Work on a better system for read-only status registers then to better support performance counters
> 
> Let me know what you think

I am fine with it! But the modification in this PR will introduce a bug back I fixed before. Could you solve it first?

Is it ok if we design a base CsrManager without performance counter to make it simpler? And we can extend that base CsrManager to a more complex one with the read only register?

2024-05-02 08:23 UTC, jorendumoulin commented
what bug?

Yes, we can have the base csr_manager with 0 read-only csrs, and then a parameter to set the number of performance counters we can read out.

2024-05-02 08:29 UTC, xiaoling-yi requested changes

2024-05-02 08:29 UTC, xiaoling-yi commented on src/main/scala/streamer/CsrManager.scala
> +  val read_csr_busy = RegNext(
This will introduce a can not reset bug in QeustaSim.  `read_csr_busy` will not be stable at the beginning. We need to explicitly reset it.

2024-05-02 08:45 UTC, jorendumoulin commented
So we should never use `RegNext` or `Reg`, but always `RegInit`?

2024-05-02 08:49 UTC, xiaoling-yi commented
Yes, I think we should use `RegInit` in case of unstable reset.

2024-05-02 08:58 UTC, xiaoling-yi approved these changes

2024-05-02 09:05 UTC, merged